CREATE TABLE ZJJS_DK_ZJDB_SQ (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ZXBH VARCHAR2(15) NOT NULL,
    REVISION INT NOT NULL,
    CREATOR VARCHAR2(100),
    CREATED_TIME TIMESTAMP(0) NOT NULL,
    UPDATOR VARCHAR2(100),
    UPDATED_TIME TIMESTAMP(0),
    JBJGBH VARCHAR2(30) NOT NULL,
    JBJGMC VARCHAR2(90) NOT NULL,
    QDBM VARCHAR2(16),
    DEL_FLAG VARCHAR2(1) NOT NULL,
    SQBH VARCHAR2(40) NOT NULL,
    SQRQ DATE NOT NULL,
    SQR VARCHAR2(60) NOT NULL,
    ZJE DECIMAL(18,2) NOT NULL,
    BJZT VARCHAR2(20) NOT NULL,
    JGZT VARCHAR2(20) NOT NULL,
    SPZT VARCHAR2(20) NOT NULL,
    WORKID VARCHAR2(100),
    LCSLID VARCHAR2(64),
    SPLCBH VARCHAR2(64),
    DQHJBH VARCHAR2(64),
    DQHJMC VARCHAR2(100),
    FJSL INT NOT NULL,
    BZ VARCHAR2(500),
    CONSTRAINT PK_DK_ZJDB_SQ PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_ZJJS_DK_ZJDB_SQ_SQBH ON ZJJS_DK_ZJDB_SQ (SQBH);
CREATE INDEX IDX_ZJJS_DK_ZJDB_SQ_SQRQ_SPZT ON ZJJS_DK_ZJDB_SQ (SQRQ, SPZT);

COMMENT ON TABLE ZJJS_DK_ZJDB_SQ IS '资金调拨申请主单';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.ID IS '主键';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.ZXBH IS '中心编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.REVISION IS '乐观锁';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.CREATOR IS '创建人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.UPDATOR IS '更新人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.JBJGBH IS '机构编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.JBJGMC IS '机构名称';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.QDBM IS '渠道编码';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.SQBH IS '申请编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.SQRQ IS '申请日期';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.SQR IS '申请人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.ZJE IS '调拨总金额';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.BJZT IS '办结状态';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.JGZT IS '结果状态';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.SPZT IS '审批状态';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.WORKID IS '工作流ID';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.LCSLID IS '流程实例ID';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.SPLCBH IS '审批流程编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.DQHJBH IS '当前环节编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.DQHJMC IS '当前环节名称';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.FJSL IS '附件数量';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SQ.BZ IS '备注';

CREATE TABLE ZJJS_DK_ZJDB_MX (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ZXBH VARCHAR2(15) NOT NULL,
    REVISION INT NOT NULL,
    CREATOR VARCHAR2(100),
    CREATED_TIME TIMESTAMP(0) NOT NULL,
    UPDATOR VARCHAR2(100),
    UPDATED_TIME TIMESTAMP(0),
    JBJGBH VARCHAR2(30) NOT NULL,
    JBJGMC VARCHAR2(90) NOT NULL,
    QDBM VARCHAR2(16),
    DEL_FLAG VARCHAR2(1) NOT NULL,
    SQBH VARCHAR2(40) NOT NULL,
    YWSLBH VARCHAR2(30) NOT NULL,
    XH INT NOT NULL,
    WDBH VARCHAR2(30) NOT NULL,
    WDMC VARCHAR2(90) NOT NULL,
    SKYH VARCHAR2(120) NOT NULL,
    SKZH VARCHAR2(60) NOT NULL,
    FKYH VARCHAR2(120) NOT NULL,
    FKZH VARCHAR2(60) NOT NULL,
    ZCZHXXID BIGINT NOT NULL,
    ZCYHDM VARCHAR2(10) NOT NULL,
    JE DECIMAL(16,2) NOT NULL,
    XTLX VARCHAR2(10) NOT NULL,
    YWLX VARCHAR2(16) NOT NULL,
    ZRZHXXID BIGINT NOT NULL,
    ZRYHDM VARCHAR2(10) NOT NULL,
    ZHAIYAO VARCHAR2(60) NOT NULL,
    JSLX VARCHAR2(10) NOT NULL,
    BEIZHU VARCHAR2(200),
    QKJE DECIMAL(18,2) NOT NULL,
    ZXJYE DECIMAL(18,2) NOT NULL,
    MXZT VARCHAR2(20) NOT NULL,
    YDZ VARCHAR2(100),
    CWXX VARCHAR2(1000),
    CONSTRAINT PK_DK_ZJDB_MX PRIMARY KEY (ID),
    CONSTRAINT FK_ZJJS_DK_ZJDB_MX_SQBH FOREIGN KEY (SQBH) REFERENCES ZJJS_DK_ZJDB_SQ (SQBH)
);

CREATE INDEX IDX_ZJJS_DK_ZJDB_MX_SQBH ON ZJJS_DK_ZJDB_MX (SQBH);
CREATE INDEX IDX_ZJJS_DK_ZJDB_MX_FKZH_MXZT ON ZJJS_DK_ZJDB_MX (FKZH, MXZT);
CREATE UNIQUE INDEX UK_ZJJS_DK_ZJDB_MX_YWSLBH ON ZJJS_DK_ZJDB_MX (YWSLBH);

COMMENT ON TABLE ZJJS_DK_ZJDB_MX IS '资金调拨申请明细';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ID IS '主键';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ZXBH IS '中心编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.REVISION IS '乐观锁';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.CREATOR IS '创建人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.UPDATOR IS '更新人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.JBJGBH IS '机构编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.JBJGMC IS '机构名称';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.QDBM IS '渠道编码';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.SQBH IS '申请编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.YWSLBH IS '业务受理编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.XH IS '行号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.WDBH IS '网点编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.WDMC IS '网点名称';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.SKYH IS '收款银行';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.SKZH IS '收款账号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.FKYH IS '付款银行';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.FKZH IS '付款账号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ZCZHXXID IS '支出账户信息ID';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ZCYHDM IS '支出银行代码';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.JE IS '调拨金额';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.XTLX IS '系统类型';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.YWLX IS '业务类型';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ZRZHXXID IS '转入账户信息ID';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ZRYHDM IS '转入银行代码';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ZHAIYAO IS '摘要';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.JSLX IS '结算类型';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.BEIZHU IS '备注';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.QKJE IS '缺口金额';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.ZXJYE IS '执行前实时可用余额';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.MXZT IS '明细状态';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.YDZ IS '幂等值';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MX.CWXX IS '错误信息';

CREATE TABLE ZJJS_DK_ZJDB_SF_RZ (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ZXBH VARCHAR2(15) NOT NULL,
    REVISION INT NOT NULL,
    CREATOR VARCHAR2(100),
    CREATED_TIME TIMESTAMP(0) NOT NULL,
    UPDATOR VARCHAR2(100),
    UPDATED_TIME TIMESTAMP(0),
    JBJGBH VARCHAR2(30) NOT NULL,
    JBJGMC VARCHAR2(90) NOT NULL,
    QDBM VARCHAR2(16),
    DEL_FLAG VARCHAR2(1) NOT NULL,
    SQBH VARCHAR2(40) NOT NULL,
    MXBH VARCHAR2(60) NOT NULL,
    SFJE DECIMAL(18,2) NOT NULL,
    SFYY VARCHAR2(200) NOT NULL,
    SFSJ TIMESTAMP(0) NOT NULL,
    CONSTRAINT PK_DK_ZJDB_SF_RZ PRIMARY KEY (ID),
    CONSTRAINT FK_ZJJS_DK_ZJDB_SF_RZ_SQBH FOREIGN KEY (SQBH) REFERENCES ZJJS_DK_ZJDB_SQ (SQBH)
);

CREATE INDEX IDX_ZJJS_DK_ZJDB_SF_RZ_SQBH ON ZJJS_DK_ZJDB_SF_RZ (SQBH);

COMMENT ON TABLE ZJJS_DK_ZJDB_SF_RZ IS '资金调拨失败释放日志';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.ID IS '主键';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.ZXBH IS '中心编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.REVISION IS '乐观锁';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.CREATOR IS '创建人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.UPDATOR IS '更新人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.JBJGBH IS '机构编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.JBJGMC IS '机构名称';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.QDBM IS '渠道编码';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.SQBH IS '申请编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.MXBH IS '明细标识';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.SFJE IS '释放金额';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.SFYY IS '释放原因';
COMMENT ON COLUMN ZJJS_DK_ZJDB_SF_RZ.SFSJ IS '释放时间';

CREATE TABLE ZJJS_DK_ZJDB_MD_RZ (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ZXBH VARCHAR2(15) NOT NULL,
    REVISION INT NOT NULL,
    CREATOR VARCHAR2(100),
    CREATED_TIME TIMESTAMP(0) NOT NULL,
    UPDATOR VARCHAR2(100),
    UPDATED_TIME TIMESTAMP(0),
    JBJGBH VARCHAR2(30) NOT NULL,
    JBJGMC VARCHAR2(90) NOT NULL,
    QDBM VARCHAR2(16),
    DEL_FLAG VARCHAR2(1) NOT NULL,
    YDZ VARCHAR2(100) NOT NULL,
    SQBH VARCHAR2(40) NOT NULL,
    MXBH VARCHAR2(60) NOT NULL,
    QQZY VARCHAR2(200) NOT NULL,
    CLJG VARCHAR2(20) NOT NULL,
    CLSJ TIMESTAMP(0) NOT NULL,
    CONSTRAINT PK_DK_ZJDB_MD_RZ PRIMARY KEY (ID),
    CONSTRAINT FK_ZJJS_DK_ZJDB_MD_RZ_SQBH FOREIGN KEY (SQBH) REFERENCES ZJJS_DK_ZJDB_SQ (SQBH)
);

CREATE UNIQUE INDEX UK_ZJJS_DK_ZJDB_MD_RZ_YDZ ON ZJJS_DK_ZJDB_MD_RZ (YDZ);
CREATE INDEX IDX_ZJJS_DK_ZJDB_MD_RZ_SQBH ON ZJJS_DK_ZJDB_MD_RZ (SQBH);

COMMENT ON TABLE ZJJS_DK_ZJDB_MD_RZ IS '资金调拨幂等防重日志';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.ID IS '主键';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.ZXBH IS '中心编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.REVISION IS '乐观锁';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.CREATOR IS '创建人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.UPDATOR IS '更新人';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.JBJGBH IS '机构编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.JBJGMC IS '机构名称';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.QDBM IS '渠道编码';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.DEL_FLAG IS '删除标志';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.YDZ IS '幂等值';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.SQBH IS '申请编号';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.MXBH IS '明细标识';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.QQZY IS '请求摘要';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.CLJG IS '处理结果';
COMMENT ON COLUMN ZJJS_DK_ZJDB_MD_RZ.CLSJ IS '处理时间';
