-- =====================================================================
-- 一户通批量任务表增加 result_dispatch_status 字段（入口说明）
-- 请按目标库类型选择对应脚本执行，勿混用：
--
--   MySQL：20260529-zjjs_zj_yht_batch_task增加result_dispatch_status-MySQL执行脚本.sql
--   达梦 ：20260529-zjjs_zj_yht_batch_task增加result_dispatch_status-达梦执行脚本.sql
-- =====================================================================
