-- =====================================================================
-- 业务收支预算执行情况组 - 达梦执行脚本
-- 适用数据库：达梦 DM
-- 说明：仅覆盖业务收支预算执行情况主表、机构执行明细表
-- 表名与字段名统一使用大写，不使用引号
-- =====================================================================

-- =====================================================================
-- 1. 业务收支预算执行情况主表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZYSZXQKB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    YF VARCHAR2(2) NOT NULL COMMENT '月份',
    BBRQ DATE COMMENT '报表日期',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    SHYJ VARCHAR2(500) COMMENT '审核意见',
    QSSJ TIMESTAMP(0) COMMENT '最近取数时间',
    QSCS INT DEFAULT 0 COMMENT '取数次数',
    TJSJ TIMESTAMP(0) COMMENT '提交时间',
    SPSJ TIMESTAMP(0) COMMENT '审批时间',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    SDSJ TIMESTAMP(0) COMMENT '锁定时间',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZYSZXQKB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZYSZXQKB IS '业务收支预算执行情况主表';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZYSZXQKB_ND ON CWHS_ZJYJS_YWSZYSZXQKB (ND, YF, DEL_FLAG);
CREATE INDEX IDX_CWHS_ZJYJS_YWSZYSZXQKB_BBBH ON CWHS_ZJYJS_YWSZYSZXQKB (BBBH);

-- =====================================================================
-- 2. 业务收支预算执行情况机构明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZYSZXQKFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    YF VARCHAR2(2) NOT NULL COMMENT '月份',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '行状态',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    TJSJ TIMESTAMP(0) COMMENT '提交时间',
    THYY VARCHAR2(500) COMMENT '退回原因',
    SR_BNYSS DECIMAL(20,4) COMMENT '收入本年预算数',
    SR_BNSJS DECIMAL(20,4) COMMENT '收入本年实绩数',
    SR_WBNYSSBL DECIMAL(20,6) COMMENT '收入为本年预算数比率',
    SR_SNTQS DECIMAL(20,4) COMMENT '收入上年同期数',
    SR_TBZZ DECIMAL(20,6) COMMENT '收入同比增长率',
    ZC_BNYSS DECIMAL(20,4) COMMENT '支出本年预算数',
    ZC_BNSJS DECIMAL(20,4) COMMENT '支出本年实绩数',
    ZC_WBNYSSBL DECIMAL(20,6) COMMENT '支出为本年预算数比率',
    ZC_SNTQS DECIMAL(20,4) COMMENT '支出上年同期数',
    ZC_TBZZ DECIMAL(20,6) COMMENT '支出同比增长率',
    ZZSY_BNYSS DECIMAL(20,4) COMMENT '增值收益本年预算数',
    ZZSY_BNSJS DECIMAL(20,4) COMMENT '增值收益本年实绩数',
    ZZSY_WBNYSSBL DECIMAL(20,6) COMMENT '增值收益为本年预算数比率',
    ZZSY_SNTQS DECIMAL(20,4) COMMENT '增值收益上年同期数',
    ZZSY_TBZZ DECIMAL(20,6) COMMENT '增值收益同比增长率',
    QSZT VARCHAR2(2) COMMENT '取数状态',
    QSCWYY VARCHAR2(500) COMMENT '取数错误原因',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZYSZXQKFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZYSZXQKFB IS '业务收支预算执行情况机构明细表';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZYSZXQKFB_MAIN_HSJG ON CWHS_ZJYJS_YWSZYSZXQKFB (MAIN_ID, HSJGBH);
CREATE INDEX IDX_CWHS_ZJYJS_YWSZYSZXQKFB_BBBH_HSJG ON CWHS_ZJYJS_YWSZYSZXQKFB (BBBH, HSJGBH, DEL_FLAG);

