-- =====================================================================
-- 归集使用决算组 - 达梦执行脚本
-- 适用数据库：达梦 DM
-- 说明：仅覆盖归集使用决算总表主表、总表明细表、附表明细表
-- 表名与字段名统一使用大写、不使用引号
-- =====================================================================

-- =====================================================================
-- 1. 归集使用决算总表主表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_GJSYJSZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '报表状态',
    QSSJ TIMESTAMP(0) COMMENT '最近同步时间',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    SHYJ VARCHAR2(500) COMMENT '审核意见',
    SPSJ TIMESTAMP(0) COMMENT '审批时间',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    SDSJ TIMESTAMP(0) COMMENT '锁定时间',
    CONSTRAINT PK_CWHS_ZJYJS_GJSYJSZB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_GJSYJSZB IS '归集使用决算总表主表';
CREATE INDEX IDX_CWHS_ZJYJS_GJSYJSZB_ND ON CWHS_ZJYJS_GJSYJSZB (ND, DEL_FLAG);
CREATE INDEX IDX_CWHS_ZJYJS_GJSYJSZB_BBBH ON CWHS_ZJYJS_GJSYJSZB (BBBH);

-- =====================================================================
-- 2. 归集使用决算总表明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_GJSYJSZMX (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    HANGXH INT NOT NULL COMMENT '行序号',
    FLMC VARCHAR2(50) COMMENT '分类名称',
    XMBM VARCHAR2(50) NOT NULL COMMENT '项目编码',
    XMMC VARCHAR2(100) NOT NULL COMMENT '项目名称',
    SFGS CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否公式行',
    SFBSY CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否不适用行',
    SNTQS DECIMAL(20,4) COMMENT '上年同期数',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    BNSJS DECIMAL(20,4) COMMENT '本年实绩数',
    YSWCL DECIMAL(20,6) COMMENT '预算完成率',
    BSTQZZ DECIMAL(20,6) COMMENT '比上年同期增长',
    CONSTRAINT PK_CWHS_ZJYJS_GJSYJSZMX PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_GJSYJSZMX IS '归集使用决算总表明细';
CREATE INDEX IDX_CWHS_ZJYJS_GJSYJSZMX_MAIN ON CWHS_ZJYJS_GJSYJSZMX (MAIN_ID, HANGXH);
CREATE INDEX IDX_CWHS_ZJYJS_GJSYJSZMX_BBBH ON CWHS_ZJYJS_GJSYJSZMX (BBBH, XMBM);

-- =====================================================================
-- 3. 归集使用决算附表明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_GJSYJSFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '行状态',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    QSZT VARCHAR2(2) COMMENT '来源同步状态',
    QSCWYY VARCHAR2(500) COMMENT '同步错误原因',
    TJSJ TIMESTAMP(0) COMMENT '提交时间',
    GJTQ_NCYE DECIMAL(20,4) COMMENT '归集提取年初余额',
    GJTQ_DNGJS DECIMAL(20,4) COMMENT '归集提取当年归集数',
    GJTQ_DNTQS DECIMAL(20,4) COMMENT '归集提取当年提取数',
    GJTQ_DNTCDJZJ DECIMAL(20,4) COMMENT '归集提取当年统筹调剂资金',
    GJTQ_NMYE DECIMAL(20,4) COMMENT '归集提取年末余额',
    GRDK_NCYE DECIMAL(20,4) COMMENT '个人贷款年初余额',
    GRDK_DNFFS DECIMAL(20,4) COMMENT '个人贷款当年发放数',
    GRDK_DNSHS DECIMAL(20,4) COMMENT '个人贷款当年收回数',
    GRDK_DNGZSDKZC DECIMAL(20,4) COMMENT '个人贷款当年公转商贷款转出',
    GRDK_NMYE DECIMAL(20,4) COMMENT '个人贷款年末余额',
    GRDK_DKYEZBGJYE DECIMAL(20,6) COMMENT '个人贷款余额占归集余额比',
    GDTZ_NCYE DECIMAL(20,4) COMMENT '国债投资年初余额',
    GDTZ_DNZJS DECIMAL(20,4) COMMENT '国债投资当年增加数',
    GDTZ_DNHSS DECIMAL(20,4) COMMENT '国债投资当年回收数',
    GDTZ_NMYE DECIMAL(20,4) COMMENT '国债投资年末余额',
    GDTZ_YEZBGJYE DECIMAL(20,6) COMMENT '国债投资余额占归集余额比',
    CONSTRAINT PK_CWHS_ZJYJS_GJSYJSFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_GJSYJSFB IS '归集使用决算附表明细';
CREATE INDEX IDX_CWHS_ZJYJS_GJSYJSFB_MAIN_HSJG ON CWHS_ZJYJS_GJSYJSFB (MAIN_ID, HSJGBH);
CREATE INDEX IDX_CWHS_ZJYJS_GJSYJSFB_BBBH_HSJG ON CWHS_ZJYJS_GJSYJSFB (BBBH, HSJGBH, DEL_FLAG);
