-- =====================================================================
-- 资金预决算及执行情况 - 达梦执行总脚本 (V7 系统字段15项修正版)
-- 适用数据库：达梦 DM
-- 说明：表名与字段名统一使用大写、不使用引号；所有表统一采用用户确认的15个系统字段
-- =====================================================================

-- =====================================================================
-- 1. 资金使用预算总表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZJSYYSZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_ZJSYYSZB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZJSYYSZB IS '资金使用预算总表';

-- =====================================================================
-- 2. 资金使用预算附表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZJSYYFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    HANGXH INT NOT NULL COMMENT '报表行序号',
    XMLB VARCHAR2(50) COMMENT '项目类别',
    XMMC VARCHAR2(100) COMMENT '项目名称',
    SNYSS DECIMAL(20,4) COMMENT '上年预算数',
    SNSJS DECIMAL(20,4) COMMENT '上年实际数',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    BNSJS DECIMAL(20,4) COMMENT '本年实际数',
    CONSTRAINT PK_CWHS_ZJYJS_ZJSYYFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZJSYYFB IS '资金使用预算附表';
CREATE INDEX IDX_CWHS_ZJYJS_ZJSYYFB_MH ON CWHS_ZJYJS_ZJSYYFB (MAIN_ID, HSJGBH);

-- =====================================================================
-- 3. 业务收支预算总表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZYSZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZYSZB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZYSZB IS '业务收支预算总表';

-- =====================================================================
-- 4. 业务收支预算附表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZYSFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    HANGXH INT NOT NULL COMMENT '报表行序号',
    XMMC VARCHAR2(100) COMMENT '项目名称',
    SNSJS DECIMAL(20,4) COMMENT '上年实际数',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZYSFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZYSFB IS '业务收支预算附表';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZYSFB_MH ON CWHS_ZJYJS_YWSZYSFB (MAIN_ID, HSJGBH);

-- =====================================================================
-- 5. 资金使用预算执行情况表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZJSYYSZXQKB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    YF VARCHAR2(2) NOT NULL COMMENT '月份',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_ZJSYYSZXQKB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZJSYYSZXQKB IS '资金使用预算执行情况表';

-- =====================================================================
-- 6. 资金使用预算执行情况明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZJSYYSZXQKFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    HANGXH INT NOT NULL COMMENT '报表行序号',
    XMLB VARCHAR2(50) COMMENT '项目类别',
    XMMC VARCHAR2(100) COMMENT '项目名称',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    BNSJS DECIMAL(20,4) COMMENT '本年实际数',
    SNTQS DECIMAL(20,4) COMMENT '上年同期数',
    CONSTRAINT PK_CWHS_ZJYJS_ZJSYYSZXQKFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZJSYYSZXQKFB IS '资金使用预算执行情况明细表';
CREATE INDEX IDX_CWHS_ZJYJS_ZJSYYSZXQKFB_MH ON CWHS_ZJYJS_ZJSYYSZXQKFB (MAIN_ID, HSJGBH);

-- =====================================================================
-- 7. 业务收支预算执行情况表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZYSZXQKB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    YF VARCHAR2(2) NOT NULL COMMENT '月份',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZYSZXQKB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZYSZXQKB IS '业务收支预算执行情况表';

-- =====================================================================
-- 8. 业务收支预算执行情况明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZYSZXQKFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    HANGXH INT NOT NULL COMMENT '报表行序号',
    XMLB VARCHAR2(50) COMMENT '项目类别(收入/支出)',
    XMMC VARCHAR2(100) COMMENT '项目名称',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    BNSJS DECIMAL(20,4) COMMENT '本年实际数',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZYSZXQKFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZYSZXQKFB IS '业务收支预算执行情况明细表';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZYSZXQKFB_MH ON CWHS_ZJYJS_YWSZYSZXQKFB (MAIN_ID, HSJGBH);

-- =====================================================================
-- 9. 归集使用决算总表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_GJSYJSZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_GJSYJSZB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_GJSYJSZB IS '归集使用决算总表';

-- =====================================================================
-- 10. 归集使用决算附表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_GJSYJSFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    HANGXH INT NOT NULL COMMENT '报表行序号',
    XMMC VARCHAR2(100) COMMENT '项目名称',
    SNTQS DECIMAL(20,4) COMMENT '上年同期数',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    BNSJS DECIMAL(20,4) COMMENT '本年实际数',
    CONSTRAINT PK_CWHS_ZJYJS_GJSYJSFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_GJSYJSFB IS '归集使用决算附表';
CREATE INDEX IDX_CWHS_ZJYJS_GJSYJSFB_MH ON CWHS_ZJYJS_GJSYJSFB (MAIN_ID, HSJGBH);

-- =====================================================================
-- 11. 业务收支决算总表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZJSZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZJSZB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZJSZB IS '业务收支决算总表';

-- =====================================================================
-- 12. 业务收支决算附表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZJSFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    HANGXH INT NOT NULL COMMENT '报表行序号',
    XMMC VARCHAR2(100) COMMENT '项目名称',
    SNTQS DECIMAL(20,4) COMMENT '上年同期数',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    BNSJS DECIMAL(20,4) COMMENT '本年实际数',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZJSFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZJSFB IS '业务收支决算附表';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZJSFB_MH ON CWHS_ZJYJS_YWSZJSFB (MAIN_ID, HSJGBH);

-- =====================================================================
-- 13. 增值收益分配情况总表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZZSYFPQKZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_ZZSYFPQKZB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZZSYFPQKZB IS '增值收益分配情况总表';

-- =====================================================================
-- 14. 增值收益分配情况附表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZZSYFPQKFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    HANGXH INT NOT NULL COMMENT '报表行序号',
    XMLB VARCHAR2(50) COMMENT '项目类别(如:贷款风险准备金)',
    XMMC VARCHAR2(100) COMMENT '项目名称(如:当年分配)',
    SNSJS DECIMAL(20,4) COMMENT '上年实际数',
    BNSJS DECIMAL(20,4) COMMENT '本年实际数',
    CONSTRAINT PK_CWHS_ZJYJS_ZZSYFPQKFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZZSYFPQKFB IS '增值收益分配情况附表';
CREATE INDEX IDX_CWHS_ZJYJS_ZZSYFPQKFB_MH ON CWHS_ZJYJS_ZZSYFPQKFB (MAIN_ID, HSJGBH);

-- =====================================================================
-- 15. 扩面工作完成情况表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_KMGZWCQKB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) COMMENT '报表编号',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    JZRQ DATE NOT NULL COMMENT '截止日期',
    BBZT VARCHAR2(2) DEFAULT '0' NOT NULL COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    CONSTRAINT PK_CWHS_ZJYJS_KMGZWCQKB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_KMGZWCQKB IS '扩面工作完成情况表';

-- =====================================================================
-- 16. 扩面工作完成情况明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_KMGZWCQKFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    ZBMC VARCHAR2(100) COMMENT '指标名称',
    DW VARCHAR2(20) COMMENT '单位(人/%)',
    ZBZ DECIMAL(20,4) COMMENT '指标数值',
    CONSTRAINT PK_CWHS_ZJYJS_KMGZWCQKFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_KMGZWCQKFB IS '扩面工作完成情况明细表';
CREATE INDEX IDX_CWHS_ZJYJS_KMGZWCQKFB_MH ON CWHS_ZJYJS_KMGZWCQKFB (MAIN_ID, HSJGBH);
