-- =====================================================================
-- 业务收支决算组 - 达梦执行脚本
-- 适用数据库：达梦 DM
-- 说明：仅覆盖业务收支决算总表主表、总表明细表、附表明细表
-- 表名与字段名统一使用大写、不使用引号
-- =====================================================================

-- =====================================================================
-- 1. 业务收支决算总表主表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZJSZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '报表状态',
    QSSJ TIMESTAMP(0) COMMENT '最近同步时间',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    SHYJ VARCHAR2(500) COMMENT '审核意见',
    SPSJ TIMESTAMP(0) COMMENT '审批时间',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    SDSJ TIMESTAMP(0) COMMENT '锁定时间',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZJSZB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZJSZB IS '业务收支决算总表主表';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZJSZB_ND ON CWHS_ZJYJS_YWSZJSZB (ND, DEL_FLAG);
CREATE INDEX IDX_CWHS_ZJYJS_YWSZJSZB_BBBH ON CWHS_ZJYJS_YWSZJSZB (BBBH);

-- =====================================================================
-- 2. 业务收支决算总表明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZJSZMX (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    HANGXH INT NOT NULL COMMENT '行序号',
    XMBM VARCHAR2(50) NOT NULL COMMENT '项目编码',
    XMMC VARCHAR2(100) NOT NULL COMMENT '项目名称',
    SFGS CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否公式行',
    SFBSY CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否不适用行',
    SNTQS DECIMAL(20,4) COMMENT '上年同期数',
    BNYSS DECIMAL(20,4) COMMENT '本年预算数',
    BNSJS DECIMAL(20,4) COMMENT '本年实绩数',
    YSWCL DECIMAL(20,6) COMMENT '预算完成率',
    BSTQZZ DECIMAL(20,6) COMMENT '比上年同期增长',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZJSZMX PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZJSZMX IS '业务收支决算总表明细';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZJSZMX_MAIN ON CWHS_ZJYJS_YWSZJSZMX (MAIN_ID, HANGXH);
CREATE INDEX IDX_CWHS_ZJYJS_YWSZJSZMX_BBBH ON CWHS_ZJYJS_YWSZJSZMX (BBBH, XMBM);

-- =====================================================================
-- 3. 业务收支决算附表明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_YWSZJSFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '报表状态',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    QSZT VARCHAR2(2) COMMENT '来源同步状态',
    QSCWYY VARCHAR2(500) COMMENT '同步错误原因',
    TJSJ TIMESTAMP(0) COMMENT '提交时间',
    YWSR_ZFGJJLXS DECIMAL(20,4) COMMENT '住房公积金利息收入',
    YWSR_ZZSYLXS DECIMAL(20,4) COMMENT '增值收益利息收入',
    YWSR_WTDKLXS DECIMAL(20,4) COMMENT '委托贷款利息收入',
    YWSR_GDTZSR DECIMAL(20,4) COMMENT '国债投资收入',
    YWSR_QTSR DECIMAL(20,4) COMMENT '其他收入',
    YWSR_HJ DECIMAL(20,4) COMMENT '业务收入合计',
    YWSZ_ZFGJJLXZC DECIMAL(20,4) COMMENT '住房公积金利息支出',
    YWSZ_GJSXFZC DECIMAL(20,4) COMMENT '住房公积金归集手续费支出',
    YWSZ_WTDKSXFZC DECIMAL(20,4) COMMENT '委托贷款手续费支出',
    YWSZ_QTZC DECIMAL(20,4) COMMENT '其他支出',
    YWSZ_HJ DECIMAL(20,4) COMMENT '业务支出合计',
    ZZSY DECIMAL(20,4) COMMENT '增值收益',
    CONSTRAINT PK_CWHS_ZJYJS_YWSZJSFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_YWSZJSFB IS '业务收支决算附表明细';
CREATE INDEX IDX_CWHS_ZJYJS_YWSZJSFB_MAIN_HSJG ON CWHS_ZJYJS_YWSZJSFB (MAIN_ID, HSJGBH);
CREATE INDEX IDX_CWHS_ZJYJS_YWSZJSFB_BBBH_HSJG ON CWHS_ZJYJS_YWSZJSFB (BBBH, HSJGBH, DEL_FLAG);
