-- =====================================================================
-- 资金使用预算执行情况组 - 达梦执行脚本
-- 适用数据库：达梦 DM
-- 说明：仅覆盖资金使用预算执行情况主表、机构执行明细表
-- 表名与字段名统一使用大写，不使用引号
-- =====================================================================

-- =====================================================================
-- 1. 资金使用预算执行情况主表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZJSYYSZXQKB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    YF VARCHAR2(2) NOT NULL COMMENT '月份',
    BBRQ DATE COMMENT '报表日期',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '报表状态',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    SHYJ VARCHAR2(500) COMMENT '审核意见',
    QSSJ TIMESTAMP(0) COMMENT '最近取数时间',
    QSCS INT DEFAULT 0 COMMENT '取数次数',
    TJSJ TIMESTAMP(0) COMMENT '提交时间',
    SPSJ TIMESTAMP(0) COMMENT '审批时间',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    SDSJ TIMESTAMP(0) COMMENT '锁定时间',
    CONSTRAINT PK_CWHS_ZJYJS_ZJSYYSZXQKB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZJSYYSZXQKB IS '资金使用预算执行情况主表';
CREATE INDEX IDX_CWHS_ZJYJS_ZJSYYSZXQKB_ND ON CWHS_ZJYJS_ZJSYYSZXQKB (ND, YF, DEL_FLAG);
CREATE INDEX IDX_CWHS_ZJYJS_ZJSYYSZXQKB_BBBH ON CWHS_ZJYJS_ZJSYYSZXQKB (BBBH);

-- =====================================================================
-- 2. 资金使用预算执行情况机构明细表
-- =====================================================================
CREATE TABLE CWHS_ZJYJS_ZJSYYSZXQKFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    YF VARCHAR2(2) NOT NULL COMMENT '月份',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '行状态',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    TJSJ TIMESTAMP(0) COMMENT '提交时间',
    THYY VARCHAR2(500) COMMENT '退回原因',
    GJTQ_SYMYE DECIMAL(20,4) COMMENT '归集提取上年末余额',
    GJTQ_BNGJYS DECIMAL(20,4) COMMENT '归集提取本年归集预算数',
    GJTQ_BNGJSJ DECIMAL(20,4) COMMENT '归集提取本年归集实绩数',
    GJTQ_GJWCL DECIMAL(20,6) COMMENT '归集提取归集完成预算率',
    GJTQ_SNGJTQS DECIMAL(20,4) COMMENT '归集提取上年归集同期数',
    GJTQ_GJTBZZ DECIMAL(20,6) COMMENT '归集提取归集同比增长率',
    GJTQ_BNTQYS DECIMAL(20,4) COMMENT '归集提取本年提取预算数',
    GJTQ_BNTQSJ DECIMAL(20,4) COMMENT '归集提取本年提取实绩数',
    GJTQ_TQWCL DECIMAL(20,6) COMMENT '归集提取提取完成预算率',
    GJTQ_SNTQTQS DECIMAL(20,4) COMMENT '归集提取上年提取同期数',
    GJTQ_TQTBZZ DECIMAL(20,6) COMMENT '归集提取提取同比增长率',
    GJTQ_DNTCTJZJ DECIMAL(20,4) COMMENT '归集提取当年统筹调剂资金',
    GJTQ_QMYE DECIMAL(20,4) COMMENT '归集提取期末余额',
    GRDK_SYMYE DECIMAL(20,4) COMMENT '个人贷款上年末余额',
    GRDK_BNFFYS DECIMAL(20,4) COMMENT '个人贷款本年发放预算数',
    GRDK_BNFFSJ DECIMAL(20,4) COMMENT '个人贷款本年发放实绩数',
    GRDK_FFWCL DECIMAL(20,6) COMMENT '个人贷款发放完成预算率',
    GRDK_SNFFTQS DECIMAL(20,4) COMMENT '个人贷款上年发放同期数',
    GRDK_FFTBZZ DECIMAL(20,6) COMMENT '个人贷款发放同比增长率',
    GRDK_BNSHYS DECIMAL(20,4) COMMENT '个人贷款本年收回预算数',
    GRDK_BNSHSJ DECIMAL(20,4) COMMENT '个人贷款本年收回实绩数',
    GRDK_SHWCL DECIMAL(20,6) COMMENT '个人贷款收回完成预算率',
    GRDK_SNSHTQS DECIMAL(20,4) COMMENT '个人贷款上年收回同期数',
    GRDK_SHTBZZ DECIMAL(20,6) COMMENT '个人贷款收回同比增长率',
    GRDK_DNGZSDKZC DECIMAL(20,4) COMMENT '个人贷款当年公转商贷款转出',
    GRDK_QMYE DECIMAL(20,4) COMMENT '个人贷款期末余额',
    GRDK_YQDK DECIMAL(20,4) COMMENT '个人贷款逾期贷款',
    GRDK_YQDKL DECIMAL(20,6) COMMENT '个人贷款逾期贷款率',
    DKYEZBGJYE DECIMAL(20,6) COMMENT '个人贷款余额占归集余额比',
    QSZT VARCHAR2(2) COMMENT '取数状态',
    QSCWYY VARCHAR2(500) COMMENT '取数错误原因',
    CONSTRAINT PK_CWHS_ZJYJS_ZJSYYSZXQKFB PRIMARY KEY (ID)
);
COMMENT ON TABLE CWHS_ZJYJS_ZJSYYSZXQKFB IS '资金使用预算执行情况机构明细表';
CREATE INDEX IDX_CWHS_ZJYJS_ZJSYYSZXQKFB_MAIN_HSJG ON CWHS_ZJYJS_ZJSYYSZXQKFB (MAIN_ID, HSJGBH);
CREATE INDEX IDX_CWHS_ZJYJS_ZJSYYSZXQKFB_BBBH_HSJG ON CWHS_ZJYJS_ZJSYYSZXQKFB (BBBH, HSJGBH, DEL_FLAG);

