-- 增值收益分配情况组 - 达梦执行脚本
-- 生成日期：2026-06-03

CREATE TABLE CWHS_ZJYJS_ZZSYFPQKZB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BZDW VARCHAR2(100) DEFAULT '嘉兴市住房公积金管理服务中心（全市）' COMMENT '编制单位',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '报表状态',
    QSSJ TIMESTAMP(0) COMMENT '最近同步时间',
    DWFZR VARCHAR2(50) COMMENT '单位负责人',
    KJZG VARCHAR2(50) COMMENT '会计主管',
    ZBR VARCHAR2(50) COMMENT '制表人',
    SHYJ VARCHAR2(500) COMMENT '审核意见',
    SPSJ TIMESTAMP(0) COMMENT '审批时间',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    SDSJ TIMESTAMP(0) COMMENT '锁定时间',
    CONSTRAINT PK_CWHS_ZJYJS_ZZSYFPQKZB PRIMARY KEY (ID)
);

COMMENT ON TABLE CWHS_ZJYJS_ZZSYFPQKZB IS '增值收益分配情况总表主表';
CREATE UNIQUE INDEX UK_CWHS_ZJYJS_ZZSYFPQKZB_BBBH ON CWHS_ZJYJS_ZZSYFPQKZB (BBBH);
CREATE INDEX IDX_CWHS_ZJYJS_ZZSYFPQKZB_ND ON CWHS_ZJYJS_ZZSYFPQKZB (ND, DEL_FLAG);

CREATE TABLE CWHS_ZJYJS_ZZSYFPQKZMX (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    HANGXH INT NOT NULL COMMENT '行序号',
    XMBM VARCHAR2(50) NOT NULL COMMENT '项目编码',
    XMMC VARCHAR2(100) NOT NULL COMMENT '项目名称',
    XMSM VARCHAR2(100) COMMENT '项目说明',
    SFGS CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否公式行',
    SNSJS DECIMAL(20,4) COMMENT '上年实绩数',
    BNSJS DECIMAL(20,4) COMMENT '本年实绩数',
    TBZZ DECIMAL(20,6) COMMENT '同比增长',
    CONSTRAINT PK_CWHS_ZJYJS_ZZSYFPQKZMX PRIMARY KEY (ID)
);

COMMENT ON TABLE CWHS_ZJYJS_ZZSYFPQKZMX IS '增值收益分配情况总表明细';
CREATE INDEX IDX_CWHS_ZJYJS_ZZSYFPQKZMX_MAIN ON CWHS_ZJYJS_ZZSYFPQKZMX (MAIN_ID, HANGXH);
CREATE INDEX IDX_CWHS_ZJYJS_ZZSYFPQKZMX_BBBH ON CWHS_ZJYJS_ZZSYFPQKZMX (BBBH, XMBM);

CREATE TABLE CWHS_ZJYJS_ZZSYFPQKFB (
    ID BIGINT NOT NULL COMMENT 'id',
    ZXBH NVARCHAR(15) NOT NULL COMMENT '中心编号',
    REVISION INT NOT NULL COMMENT '乐观锁',
    CREATOR NVARCHAR(100) COMMENT '创建人',
    CREATED_TIME TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '创建时间',
    UPDATOR NVARCHAR(100) COMMENT '更新人',
    UPDATED_TIME TIMESTAMP(0) COMMENT '更新时间',
    JBJGBH NVARCHAR(30) NOT NULL COMMENT '机构编号',
    JBJGMC NVARCHAR(90) NOT NULL COMMENT '机构名称',
    WDBH NVARCHAR(30) COMMENT '网点编号',
    WDMC NVARCHAR(90) COMMENT '网点名称',
    QDLX NVARCHAR(10) COMMENT '渠道类型',
    QDBM NVARCHAR(16) COMMENT '渠道编码',
    DEL_FLAG NVARCHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
    HSJGBH NVARCHAR(10) NOT NULL DEFAULT '01' COMMENT '核算机构编号',
    MAIN_ID BIGINT NOT NULL COMMENT '主表ID',
    BBBH VARCHAR2(50) NOT NULL COMMENT '报表编号',
    ND VARCHAR2(4) NOT NULL COMMENT '年度',
    BBZT VARCHAR2(2) NOT NULL DEFAULT '0' COMMENT '报表状态',
    SFSD CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否锁定',
    QSZT VARCHAR2(2) COMMENT '来源同步状态',
    QSCWYY VARCHAR2(500) COMMENT '同步错误原因',
    TJSJ TIMESTAMP(0) COMMENT '提交时间',
    DFPZZSY DECIMAL(20,4) COMMENT '待分配增值收益',
    DKFXZBJ_NCYE DECIMAL(20,4) COMMENT '贷款风险准备金年初余额',
    DKFXZBJ_DNFP DECIMAL(20,4) COMMENT '贷款风险准备金当年分配',
    DKFXZBJ_DNZC DECIMAL(20,4) COMMENT '贷款风险准备金当年支出',
    DKFXZBJ_NMYE DECIMAL(20,4) COMMENT '贷款风险准备金年末余额',
    GLFY_DNFP DECIMAL(20,4) COMMENT '管理费用当年分配',
    CSLZZFBQZJ_NCYE DECIMAL(20,4) COMMENT '城市廉租住房补充资金年初余额',
    CSLZZFBQZJ_DNFP DECIMAL(20,4) COMMENT '城市廉租住房补充资金当年分配',
    CSLZZFBQZJ_DNSJ DECIMAL(20,4) COMMENT '城市廉租住房补充资金当年上缴',
    CSLZZFBQZJ_NMYE DECIMAL(20,4) COMMENT '城市廉租住房补充资金年末余额',
    FPHJ DECIMAL(20,4) COMMENT '分配合计',
    SJSM VARCHAR2(500) COMMENT '上缴说明',
    YWLXDH VARCHAR2(100) COMMENT '业务流水号',
    CONSTRAINT PK_CWHS_ZJYJS_ZZSYFPQKFB PRIMARY KEY (ID)
);

COMMENT ON TABLE CWHS_ZJYJS_ZZSYFPQKFB IS '增值收益分配情况附表明细';
CREATE INDEX IDX_CWHS_ZJYJS_ZZSYFPQKFB_MAIN_HSJG ON CWHS_ZJYJS_ZZSYFPQKFB (MAIN_ID, HSJGBH);
CREATE INDEX IDX_CWHS_ZJYJS_ZZSYFPQKFB_BBBH_HSJG ON CWHS_ZJYJS_ZZSYFPQKFB (BBBH, HSJGBH, DEL_FLAG);
