SET ECHO OFF
SET VERIFY OFF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ACCEPT YHT_DATAFILE CHAR PROMPT 'Absolute database-server datafile path for YHT_MOCK: '
ACCEPT YHT_PASSWORD CHAR PROMPT 'Password for new YHT_MOCK user: ' HIDE
CREATE TABLESPACE YHT_MOCK_DATA DATAFILE '&YHT_DATAFILE' SIZE 128 AUTOEXTEND ON NEXT 64 MAXSIZE 4096;
CREATE USER YHT_MOCK IDENTIFIED BY "&YHT_PASSWORD" DEFAULT TABLESPACE YHT_MOCK_DATA DEFAULT INDEX TABLESPACE YHT_MOCK_DATA;
GRANT CREATE SESSION, CREATE TABLE TO YHT_MOCK;
UNDEFINE YHT_PASSWORD
UNDEFINE YHT_DATAFILE
EXIT SUCCESS
