SELECT USER;
SELECT ID, SCHEMA_VERSION, RECORD_NEXT, SCENARIO_NEXT, MIGRATION_HASH, MIGRATION_COUNTS FROM YHT_MOCK_CONTROL;
SELECT 'SETTINGS' AS DATA_TYPE, COUNT(*) AS ROW_COUNT FROM YHT_MOCK_SETTINGS
UNION ALL SELECT 'MOVEMENT_CONFIG', COUNT(*) FROM YHT_MOCK_MOVEMENT_CFG
UNION ALL SELECT 'RECORDS', COUNT(*) FROM YHT_MOCK_RECORD
UNION ALL SELECT 'PROTOCOLS', COUNT(*) FROM YHT_MOCK_PROTOCOL
UNION ALL SELECT 'TRADES', COUNT(*) FROM YHT_MOCK_TRADE
UNION ALL SELECT 'BATCHES', COUNT(*) FROM YHT_MOCK_BATCH
UNION ALL SELECT 'SCENARIOS', COUNT(*) FROM YHT_MOCK_SCENARIO
UNION ALL SELECT 'BANK_ACCOUNTS', COUNT(*) FROM YHT_MOCK_BANK_ACCOUNT
UNION ALL SELECT 'FLOWS', COUNT(*) FROM YHT_MOCK_FLOW
UNION ALL SELECT 'FLOW_ATTEMPTS', COUNT(*) FROM YHT_MOCK_FLOW_ATTEMPT
UNION ALL SELECT 'MOVEMENT_DEDUP', COUNT(*) FROM YHT_MOCK_MOVEMENT;
