WHENEVER SQLERROR EXIT FAILURE ROLLBACK
DECLARE
    CURRENT_VERSION INTEGER;
BEGIN
    SELECT SCHEMA_VERSION INTO CURRENT_VERSION FROM YHT_MOCK_CONTROL WHERE ID = 1;
    IF CURRENT_VERSION <> 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Expected schema version 1; stop and review existing schema');
    END IF;
END;
/
CREATE TABLE YHT_MOCK_BANK_ACCOUNT (
    C_BANK_ID VARCHAR(256) PRIMARY KEY,
    C_BANK_NAME CLOB,
    C_ACCOUNT_NO CLOB,
    C_ACCOUNT_NAME CLOB,
    C_ACCOUNT_BANK_ID CLOB,
    C_ENABLED SMALLINT NOT NULL,
    C_UPDATED_AT BIGINT NOT NULL
); 

ALTER TABLE YHT_MOCK_BATCH ADD C_CENTER_BANK_ID VARCHAR(256);
UPDATE YHT_MOCK_CONTROL SET SCHEMA_VERSION = 2 WHERE ID = 1 AND SCHEMA_VERSION = 1;
COMMIT;
