WHENEVER SQLERROR EXIT FAILURE ROLLBACK
DECLARE
    CURRENT_VERSION INTEGER;
BEGIN
    SELECT SCHEMA_VERSION INTO CURRENT_VERSION FROM YHT_MOCK_CONTROL WHERE ID = 1;
    IF CURRENT_VERSION <> 2 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Expected schema version 2; stop and review existing schema');
    END IF;
END;
/
CREATE TABLE YHT_MOCK_FLOW (
    C_ID VARCHAR(256) PRIMARY KEY,
    C_MOVEMENT_KEY CLOB,
    C_SOURCE_TYPE VARCHAR(256),
    C_BUSINESS_DATE VARCHAR(256),
    C_CENTER_BANK_ID VARCHAR(256),
    C_ACCT_NO VARCHAR(256),
    C_SYS_SEQ_NO VARCHAR(256),
    C_REQ_ID VARCHAR(256),
    C_BATCH_NO VARCHAR(256),
    C_TRAN_CODE CLOB,
    C_DIRECTION VARCHAR(256),
    C_AMOUNT DECIMAL(20, 2),
    C_STATUS VARCHAR(256),
    C_PAYLOAD CLOB,
    C_LAST_ERROR CLOB,
    C_VERSION BIGINT NOT NULL,
    C_ATTEMPT_COUNT BIGINT NOT NULL,
    C_CREATED_AT BIGINT NOT NULL,
    C_UPDATED_AT BIGINT NOT NULL
);
CREATE INDEX IDX_YHT_FLOW_DATE ON YHT_MOCK_FLOW (C_BUSINESS_DATE, C_ID);
CREATE INDEX IDX_YHT_FLOW_ACCOUNT ON YHT_MOCK_FLOW (C_ACCT_NO, C_STATUS);
CREATE TABLE YHT_MOCK_FLOW_ATTEMPT (
    C_ID VARCHAR(256) PRIMARY KEY,
    C_FLOW_ID VARCHAR(256) NOT NULL,
    C_OWNER_ID CLOB,
    C_FLOW_VERSION BIGINT NOT NULL,
    C_ACTION CLOB,
    C_REASON CLOB,
    C_STATUS VARCHAR(256),
    C_TARGET CLOB,
    C_REQUEST_BODY CLOB,
    C_RESPONSE_BODY CLOB,
    C_REMARK CLOB,
    C_CREATED_AT BIGINT NOT NULL,
    C_UPDATED_AT BIGINT NOT NULL
);
CREATE INDEX IDX_YHT_FLOW_ATTEMPT ON YHT_MOCK_FLOW_ATTEMPT (C_FLOW_ID, C_CREATED_AT);

UPDATE YHT_MOCK_CONTROL SET SCHEMA_VERSION = 3 WHERE ID = 1 AND SCHEMA_VERSION = 2;
COMMIT;
