WHENEVER SQLERROR EXIT FAILURE ROLLBACK
DECLARE
    CURRENT_VERSION INTEGER;
BEGIN
    SELECT SCHEMA_VERSION INTO CURRENT_VERSION FROM YHT_MOCK_CONTROL WHERE ID = 1;
    IF CURRENT_VERSION <> 3 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Expected schema version 3; stop and review existing schema');
    END IF;
END;
/
ALTER TABLE YHT_MOCK_MOVEMENT_CFG ADD COLUMN C_FALLBACK_ENABLED SMALLINT DEFAULT 0 NOT NULL;

UPDATE YHT_MOCK_CONTROL SET SCHEMA_VERSION = 4 WHERE ID = 1 AND SCHEMA_VERSION = 3;
COMMIT;
