WHENEVER SQLERROR EXIT FAILURE ROLLBACK
DECLARE
    CURRENT_VERSION INTEGER;
BEGIN
    SELECT SCHEMA_VERSION INTO CURRENT_VERSION FROM YHT_MOCK_CONTROL WHERE ID = 1;
    IF CURRENT_VERSION <> 4 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Expected schema version 4; stop and review existing schema');
    END IF;
END;
/
ALTER TABLE YHT_MOCK_RECORD ADD COLUMN C_DECRYPTED_REQUEST_BODY CLOB;
ALTER TABLE YHT_MOCK_RECORD ADD COLUMN C_DECRYPTED_RESPONSE_BODY CLOB;

UPDATE YHT_MOCK_CONTROL SET SCHEMA_VERSION = 5 WHERE ID = 1 AND SCHEMA_VERSION = 4;
COMMIT;
