-- 一户通挡板 数据库迁移：v5 -> v6
-- 变更要点：
--   1) 场景规则表 YHT_MOCK_SCENARIO 由「按中心账户强制成功/失败」精简为「账号校验规则（对手账号正则 / 是否有效 / 是否一类卡）」。
--   2) 回调配置表 YHT_MOCK_SETTINGS 增加随机模拟失败开关（randomFail / randomFailRatio）。
-- 说明：旧场景规则行的强制状态字段被丢弃；新列 C_VALID / C_CLASS1_CARD 默认 1（有效且一类卡），
--       即存量数据迁移后均按「成功」处理，行为向后兼容。

-- 1. 回调配置：新增随机失败开关（DEFAULT 在 NOT NULL 前，达梦与 H2 兼容）
ALTER TABLE YHT_MOCK_SETTINGS ADD C_RANDOM_FAIL SMALLINT DEFAULT 0 NOT NULL;
ALTER TABLE YHT_MOCK_SETTINGS ADD C_RANDOM_FAIL_RATIO DECIMAL(5, 4) DEFAULT 0.5;

-- 2. 场景规则：删除旧的强制状态 / 匹配字段
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_REQUEST_MESG_TYPE;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_MATCH_ACCT_NO;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_MATCH_ACCT_SUFFIX;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_MATCH_PROTOCOL_NO;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_MATCH_REQ_ID;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_MATCH_BATCH_NO;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_MATCH_SYS_SEQ_NO;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_FORCE_RES_FLAG;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_FORCE_STATUS;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_FORCE_RET_CODE;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_FORCE_RET_MSG;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_DISABLE_AUTO_CALLBACK;
ALTER TABLE YHT_MOCK_SCENARIO DROP COLUMN C_CALLBACK_MESG_TYPE;

-- 3. 场景规则：新增账号校验字段（DEFAULT 在 NOT NULL 前，达梦与 H2 兼容）
ALTER TABLE YHT_MOCK_SCENARIO ADD C_ACCOUNT_RULE CLOB;
ALTER TABLE YHT_MOCK_SCENARIO ADD C_VALID SMALLINT DEFAULT 1 NOT NULL;
ALTER TABLE YHT_MOCK_SCENARIO ADD C_CLASS1_CARD SMALLINT DEFAULT 1 NOT NULL;

-- 4. 版本号
UPDATE YHT_MOCK_CONTROL SET SCHEMA_VERSION = 6 WHERE ID = 1;
COMMIT;
