CREATE TABLE YHT_MOCK_CONTROL (ID INTEGER PRIMARY KEY, SCHEMA_VERSION INTEGER NOT NULL, RECORD_NEXT BIGINT NOT NULL, SCENARIO_NEXT BIGINT NOT NULL, MIGRATION_HASH VARCHAR(64), MIGRATION_COUNTS CLOB);
INSERT INTO YHT_MOCK_CONTROL (ID, SCHEMA_VERSION, RECORD_NEXT, SCENARIO_NEXT) VALUES (1, 6, 1, 1);

CREATE TABLE YHT_MOCK_SETTINGS (
    C_SINGLETON_ID INTEGER PRIMARY KEY,
    C_AUTO_PUSH_ENABLED SMALLINT NOT NULL,
    C_DEFAULT_TARGET_URL CLOB,
    C_DELAY_MS BIGINT NOT NULL,
    C_PUSH_CAPS107 SMALLINT NOT NULL,
    C_PUSH_CAPS205 SMALLINT NOT NULL,
    C_PUSH_CAPS306 SMALLINT NOT NULL,
    C_PUSH_CAPS308 SMALLINT NOT NULL,
    C_DEFAULT_PROTOCOL_RESULT CLOB,
    C_DEFAULT_TRADE_RESULT CLOB,
    C_DEFAULT_BATCH_RESULT CLOB,
    C_PROTOCOL_NOT_FOUND_CODE CLOB,
    C_PROTOCOL_NOT_FOUND_MSG CLOB,
    C_HSM_MOCK_KEY CLOB,
    C_SVS_MOCK_KEY CLOB,
    C_SVS_VERIFY_LENIENT SMALLINT NOT NULL,
    C_RANDOM_FAIL SMALLINT NOT NULL,
    C_RANDOM_FAIL_RATIO DECIMAL(5, 4)
);

CREATE TABLE YHT_MOCK_MOVEMENT_CFG (
    C_SINGLETON_ID INTEGER PRIMARY KEY,
    C_ENABLED SMALLINT NOT NULL,
    C_FALLBACK_ENABLED SMALLINT NOT NULL,
    C_TARGET_URL CLOB,
    C_RECEIVE_CODE CLOB,
    C_PAY_CODE CLOB,
    C_COUNTERPARTY_ACCOUNT CLOB,
    C_COUNTERPARTY_NAME CLOB,
    C_COUNTERPARTY_BANK CLOB,
    C_BALANCE DECIMAL(38, 2),
    C_AUTHORIZATION_ENV CLOB
);

CREATE TABLE YHT_MOCK_RECORD (
    C_ID BIGINT PRIMARY KEY,
    C_RECORD_TYPE VARCHAR(256),
    C_SOURCE CLOB,
    C_TARGET CLOB,
    C_MESG_TYPE VARCHAR(256),
    C_MESG_ID CLOB,
    C_REQ_ID VARCHAR(256),
    C_PROTOCOL_NO VARCHAR(256),
    C_BATCH_NO VARCHAR(256),
    C_SYS_SEQ_NO VARCHAR(256),
    C_STATUS VARCHAR(256),
    C_REQUEST_BODY CLOB,
    C_RESPONSE_BODY CLOB,
    C_DECRYPTED_REQUEST_BODY CLOB,
    C_DECRYPTED_RESPONSE_BODY CLOB,
    C_REMARK CLOB,
    C_CREATED_AT BIGINT NOT NULL
);

CREATE TABLE YHT_MOCK_PROTOCOL (
    C_PROTOCOL_NO VARCHAR(256) PRIMARY KEY,
    C_ACCT_NO VARCHAR(256),
    C_ACCT_NAME CLOB,
    C_CORP_NO CLOB,
    C_CUSTOMER_ID CLOB,
    C_CUSTOMER_NAME CLOB,
    C_FEE_NO_LIST CLOB,
    C_BANK_ID CLOB,
    C_PHONE CLOB,
    C_STATUS VARCHAR(256),
    C_RES_FLAG CLOB,
    C_ERROR_CODE CLOB,
    C_ERROR_MSG CLOB,
    C_SIGN_REQ_ID VARCHAR(256),
    C_AUTH_CODE CLOB,
    C_CHANGE_TYPE CLOB,
    C_SEND_TYPE CLOB,
    C_ORIG_MSG_ID CLOB,
    C_PYER_BG_NUM CLOB,
    C_QUERY_TIME CLOB,
    C_PROTOCOL_PROCESS_CODE CLOB,
    C_REMARK CLOB,
    C_CALLBACK_ENABLED SMALLINT NOT NULL,
    C_CALLBACK_MESG_TYPE CLOB,
    C_SCENARIO_NAME CLOB,
    C_UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE YHT_MOCK_TRADE (
    C_MOVEMENT_ELIGIBLE SMALLINT NOT NULL,
    C_SYS_SEQ_NO VARCHAR(256) PRIMARY KEY,
    C_REQ_ID VARCHAR(256),
    C_SERIAL_NUM CLOB,
    C_TRAN_CODE CLOB,
    C_ACCT_NO VARCHAR(256),
    C_ACCT_NAME CLOB,
    C_AMOUNT CLOB,
    C_BANK_ID CLOB,
    C_CREDITOR_ACCT_NO CLOB,
    C_CREDITOR_ACCT_NAME CLOB,
    C_CREDITOR_BANK_ID CLOB,
    C_BILL_NO CLOB,
    C_BTCH_NB CLOB,
    C_CHECK_DATE CLOB,
    C_STATUS VARCHAR(256),
    C_RES_FLAG CLOB,
    C_RET_CODE CLOB,
    C_RET_MSG CLOB,
    C_CALLBACK_ENABLED SMALLINT NOT NULL,
    C_CALLBACK_MESG_TYPE CLOB,
    C_SCENARIO_NAME CLOB,
    C_UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE YHT_MOCK_BATCH (
    C_CENTER_BANK_ID VARCHAR(256),
    C_CORP_ACCT_NO CLOB,
    C_REQUEST_FILE_NAME CLOB,
    C_MOVEMENT_ELIGIBLE SMALLINT NOT NULL,
    C_BATCH_NO VARCHAR(256) PRIMARY KEY,
    C_REQ_ID VARCHAR(256),
    C_TRAN_CODE CLOB,
    C_STATUS VARCHAR(256),
    C_RES_FLAG CLOB,
    C_ERROR_CODE CLOB,
    C_ERROR_MSG CLOB,
    C_TOTAL_COUNT CLOB,
    C_TOTAL_AMOUNT CLOB,
    C_CHECK_DATE CLOB,
    C_FILE_NAME CLOB,
    C_FILE_DATA CLOB,
    C_CALLBACK_ENABLED SMALLINT NOT NULL,
    C_CALLBACK_MESG_TYPE CLOB,
    C_SCENARIO_NAME CLOB,
    C_UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE YHT_MOCK_SCENARIO (
    C_ID BIGINT PRIMARY KEY,
    C_NAME CLOB,
    C_ENABLED SMALLINT NOT NULL,
    C_ACCOUNT_RULE CLOB,
    C_VALID SMALLINT NOT NULL,
    C_CLASS1_CARD SMALLINT NOT NULL,
    C_REMARK CLOB,
    C_UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE YHT_MOCK_MOVEMENT (MOVEMENT_KEY VARCHAR(1024) PRIMARY KEY, STATUS VARCHAR(32) NOT NULL);

CREATE INDEX IX_YM_RECORD_TIME ON YHT_MOCK_RECORD (C_CREATED_AT, C_ID);
CREATE INDEX IX_YM_PROTOCOL_ACCT ON YHT_MOCK_PROTOCOL (C_ACCT_NO, C_UPDATED_AT);
CREATE INDEX IX_YM_PROTOCOL_REQ ON YHT_MOCK_PROTOCOL (C_SIGN_REQ_ID, C_UPDATED_AT);
CREATE INDEX IX_YM_TRADE_REQ ON YHT_MOCK_TRADE (C_REQ_ID, C_UPDATED_AT);
CREATE INDEX IX_YM_BATCH_TIME ON YHT_MOCK_BATCH (C_UPDATED_AT);
CREATE INDEX IX_YM_SCENARIO_TIME ON YHT_MOCK_SCENARIO (C_UPDATED_AT);

CREATE TABLE YHT_MOCK_BANK_ACCOUNT (
    C_BANK_ID VARCHAR(256) PRIMARY KEY,
    C_BANK_NAME CLOB,
    C_ACCOUNT_NO CLOB,
    C_ACCOUNT_NAME CLOB,
    C_ACCOUNT_BANK_ID CLOB,
    C_ENABLED SMALLINT NOT NULL,
    C_UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE YHT_MOCK_FLOW (
    C_ID VARCHAR(256) PRIMARY KEY,
    C_MOVEMENT_KEY CLOB,
    C_SOURCE_TYPE VARCHAR(256),
    C_BUSINESS_DATE VARCHAR(256),
    C_CENTER_BANK_ID VARCHAR(256),
    C_ACCT_NO VARCHAR(256),
    C_SYS_SEQ_NO VARCHAR(256),
    C_REQ_ID VARCHAR(256),
    C_BATCH_NO VARCHAR(256),
    C_TRAN_CODE CLOB,
    C_DIRECTION VARCHAR(256),
    C_AMOUNT DECIMAL(20, 2),
    C_STATUS VARCHAR(256),
    C_PAYLOAD CLOB,
    C_LAST_ERROR CLOB,
    C_VERSION BIGINT NOT NULL,
    C_ATTEMPT_COUNT BIGINT NOT NULL,
    C_CREATED_AT BIGINT NOT NULL,
    C_UPDATED_AT BIGINT NOT NULL
);
CREATE INDEX IDX_YHT_FLOW_DATE ON YHT_MOCK_FLOW (C_BUSINESS_DATE, C_ID);
CREATE INDEX IDX_YHT_FLOW_ACCOUNT ON YHT_MOCK_FLOW (C_ACCT_NO, C_STATUS);
CREATE TABLE YHT_MOCK_FLOW_ATTEMPT (
    C_ID VARCHAR(256) PRIMARY KEY,
    C_FLOW_ID VARCHAR(256) NOT NULL,
    C_OWNER_ID CLOB,
    C_FLOW_VERSION BIGINT NOT NULL,
    C_ACTION CLOB,
    C_REASON CLOB,
    C_STATUS VARCHAR(256),
    C_TARGET CLOB,
    C_REQUEST_BODY CLOB,
    C_RESPONSE_BODY CLOB,
    C_REMARK CLOB,
    C_CREATED_AT BIGINT NOT NULL,
    C_UPDATED_AT BIGINT NOT NULL
);
CREATE INDEX IDX_YHT_FLOW_ATTEMPT ON YHT_MOCK_FLOW_ATTEMPT (C_FLOW_ID, C_CREATED_AT);
